package com.aetna.hc.rewards.aetna.aetnarewardrules;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class HrInfo implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public HrInfo() {
    }




}